### PR TITLE
Add Demo Link

### PR DESCRIPTION
**Pull request by halkeye**

### CODE REVIEW

**Comment by bywo** [comment]
hey @halkeye thanks for the PR! Unfortunately I haven't found time to finish up the demo page. I'll merge this in once the demo page is ready.

**Comment by halkeye** [comment]
I feel like even a partial demo is useful to see things in action.

**Comment by bywo** [comment]
Agreed. After checking out the repo, you can do `npm run examples`, and see em in the browser at `localhost:8080`.

**Comment by halkeye** [comment]
The only issue I have with that (which was my main issue) is when i come off one of those react component websites, I like to see what the project is about. Either a screenshot or a demo. Downloading and running examples is usually more effort than I'm willing to put in just at a glance.

Still, excited for flex so yay!

**Pull request closed without merging**
